export const products = [
    {
      id: 1,
      title: "Samsung Galaxy S23 Ultra",
      description: "The Samsung Galaxy S23 Ultra features a 6.8-inch AMOLED display, Snapdragon 8 Gen 2, and a quad-camera setup.",
      price: 1199.99,
      discountPercentage: 10,
      rating: 4.8,
      stock: 25,
      brand: "Samsung",
      category: "Smartphones",
      thumbnail: "https://example.com/images/samsung-galaxy-s23-ultra-thumbnail.jpg",
      images: [
        "https://example.com/images/samsung-galaxy-s23-ultra-1.jpg",
        "https://example.com/images/samsung-galaxy-s23-ultra-2.jpg",
        "https://example.com/images/samsung-galaxy-s23-ultra-3.jpg",
        "https://example.com/images/samsung-galaxy-s23-ultra-4.jpg"
      ],
    },
    {
      id: 2,
      title: "iPhone 14 Pro Max",
      description: "The iPhone 14 Pro Max comes with a 6.7-inch Super Retina XDR display, A16 Bionic chip, and a triple-camera system.",
      price: 1099.99,
      discountPercentage: 5,
      rating: 4.7,
      stock: 30,
      brand: "Apple",
      category: "Smartphones",
      thumbnail: "https://example.com/images/iphone-14-pro-max-thumbnail.jpg",
      images: [
        "https://example.com/images/iphone-14-pro-max-1.jpg",
        "https://example.com/images/iphone-14-pro-max-2.jpg",
        "https://example.com/images/iphone-14-pro-max-3.jpg",
        "https://example.com/images/iphone-14-pro-max-4.jpg"
      ],
    },
    {
      id: 3,
      title: "Google Pixel 8 Pro",
      description: "Google Pixel 8 Pro features a 6.7-inch OLED display, Google Tensor G3 chip, and a triple rear camera system.",
      price: 999.99,
      discountPercentage: 12,
      rating: 4.6,
      stock: 20,
      brand: "Google",
      category: "Smartphones",
      thumbnail: "https://example.com/images/google-pixel-8-pro-thumbnail.jpg",
      images: [
        "https://example.com/images/google-pixel-8-pro-1.jpg",
        "https://example.com/images/google-pixel-8-pro-2.jpg",
        "https://example.com/images/google-pixel-8-pro-3.jpg",
        "https://example.com/images/google-pixel-8-pro-4.jpg"
      ],
    },
    {
      id: 4,
      title: "OnePlus 11",
      description: "OnePlus 11 offers a 6.7-inch Fluid AMOLED display, Snapdragon 8 Gen 2, and a dual-camera setup.",
      price: 849.99,
      discountPercentage: 8,
      rating: 4.5,
      stock: 15,
      brand: "OnePlus",
      category: "Smartphones",
      thumbnail: "https://example.com/images/oneplus-11-thumbnail.jpg",
      images: [
        "https://example.com/images/oneplus-11-1.jpg",
        "https://example.com/images/oneplus-11-2.jpg",
        "https://example.com/images/oneplus-11-3.jpg",
        "https://example.com/images/oneplus-11-4.jpg"
      ],
    },
    {
      id: 5,
      title: "Xiaomi Mi 13 Pro",
      description: "Xiaomi Mi 13 Pro comes with a 6.73-inch AMOLED display, Snapdragon 8 Gen 2, and a Leica triple-camera system.",
      price: 799.99,
      discountPercentage: 7,
      rating: 4.4,
      stock: 18,
      brand: "Xiaomi",
      category: "Smartphones",
      thumbnail: "https://example.com/images/xiaomi-mi-13-pro-thumbnail.jpg",
      images: [
        "https://example.com/images/xiaomi-mi-13-pro-1.jpg",
        "https://example.com/images/xiaomi-mi-13-pro-2.jpg",
        "https://example.com/images/xiaomi-mi-13-pro-3.jpg",
        "https://example.com/images/xiaomi-mi-13-pro-4.jpg"
      ],
    },
    {
      id: 6,
      title: "Sony Xperia 1 IV",
      description: "The Sony Xperia 1 IV features a 6.5-inch 4K OLED display, Snapdragon 8 Gen 1, and a triple camera with Zeiss optics.",
      price: 1099.99,
      discountPercentage: 6,
      rating: 4.5,
      stock: 12,
      brand: "Sony",
      category: "Smartphones",
      thumbnail: "https://example.com/images/sony-xperia-1-iv-thumbnail.jpg",
      images: [
        "https://example.com/images/sony-xperia-1-iv-1.jpg",
        "https://example.com/images/sony-xperia-1-iv-2.jpg",
        "https://example.com/images/sony-xperia-1-iv-3.jpg",
        "https://example.com/images/sony-xperia-1-iv-4.jpg"
      ],
    },
    {
      id: 7,
      title: "Huawei P60 Pro",
      description: "Huawei P60 Pro comes with a 6.67-inch OLED display, Kirin 9000, and a quad-camera system with advanced zoom capabilities.",
      price: 949.99,
      discountPercentage: 9,
      rating: 4.4,
      stock: 22,
      brand: "Huawei",
      category: "Smartphones",
      thumbnail: "https://example.com/images/huawei-p60-pro-thumbnail.jpg",
      images: [
        "https://example.com/images/huawei-p60-pro-1.jpg",
        "https://example.com/images/huawei-p60-pro-2.jpg",
        "https://example.com/images/huawei-p60-pro-3.jpg",
        "https://example.com/images/huawei-p60-pro-4.jpg"
      ],
    },
    {
      id: 8,
      title: "Motorola Edge 40 Pro",
      description: "Motorola Edge 40 Pro features a 6.67-inch AMOLED display, Snapdragon 8 Gen 2, and a triple-camera system.",
      price: 799.99,
      discountPercentage: 7,
      rating: 4.3,
      stock: 17,
      brand: "Motorola",
      category: "Smartphones",
      thumbnail: "https://example.com/images/motorola-edge-40-pro-thumbnail.jpg",
      images: [
        "https://example.com/images/motorola-edge-40-pro-1.jpg",
        "https://example.com/images/motorola-edge-40-pro-2.jpg",
        "https://example.com/images/motorola-edge-40-pro-3.jpg",
        "https://example.com/images/motorola-edge-40-pro-4.jpg"
      ],
    },
    {
      id: 9,
      title: "Oppo Find X6 Pro",
      description: "Oppo Find X6 Pro offers a 6.82-inch AMOLED display, Snapdragon 8 Gen 2, and a Hasselblad camera system.",
      price: 899.99,
      discountPercentage: 10,
      rating: 4.6,
      stock: 21,
      brand: "Oppo",
      category: "Smartphones",
      thumbnail: "https://example.com/images/oppo-find-x6-pro-thumbnail.jpg",
      images: [
        "https://example.com/images/oppo-find-x6-pro-1.jpg",
        "https://example.com/images/oppo-find-x6-pro-2.jpg",
        "https://example.com/images/oppo-find-x6-pro-3.jpg",
        "https://example.com/images/oppo-find-x6-pro-4.jpg"
      ],
    },
    {
      id: 10,
      title: "Asus ROG Phone 7",
      description: "Asus ROG Phone 7 is designed for gamers with a 6.78-inch AMOLED display, Snapdragon 8 Gen 2, and a range of gaming enhancements.",
      price: 999.99,
      discountPercentage: 11,
      rating: 4.7,
      stock: 14,
      brand: "Asus",
      category: "Gaming Smartphones",
      thumbnail: "https://example.com/images/asus-rog-phone-7-thumbnail.jpg",
      images: [
        "https://example.com/images/asus-rog-phone-7-1.jpg",
        "https://example.com/images/asus-rog-phone-7-2.jpg",
        "https://example.com/images/asus-rog-phone-7-3.jpg",
        "https://example.com/images/asus-rog-phone-7-4.jpg"
      ],
    }
  ];
  